add apache shiro vuln check
PortSwigger/BChecks pull request #109
Opened 2023-09-12 07:34 UTC by QdghJ

Add Apache Shiro Vulnerability Detection Script, refer to https://github.com/vulhub/vulhub/blob/master/shiro/CVE-2016-4437/README.md, https://github.com/vulhub/vulhub/blob/master/shiro/CVE-2020-1957/README.md

2023-09-12 12:56 UTC, olliewuk requested changes
Firstly, thank you for the amazing contribution.

Can we ask please for the following changes before we merge?

- Clean up the two .txt files
- Split the key cracking .bcheck into its own PR and put int he /CVEd/ directory
- Leave the remaining two BChecks in /other/ as this PR

This is so we maintain repo hygiene.

Thank you in advance from all at PortSwigger.

2023-09-13 02:34 UTC, QdghJ commented
> Firstly, thank you for the amazing contribution.
> 
> Can we ask please for the following changes before we merge?
> 
> * Clean up the two .txt files
> * Split the key cracking .bcheck into its own PR and put int he /CVEd/ directory
> * Leave the remaining two BChecks in /other/ as this PR
> 
> This is so we maintain repo hygiene.
> 
> Thank you in advance from all at PortSwigger.

All txt files can be deleted. output.txt is used to locate the original key corresponding to the encrypted 'rememberMe' value. However, in future updates, I can include them in comments for easier reference. Thank you.

2023-09-13 02:36 UTC, QdghJ commented
> Firstly, thank you for the amazing contribution.
> 
> Can we ask please for the following changes before we merge?
> 
> * Clean up the two .txt files
> * Split the key cracking .bcheck into its own PR and put int he /CVEd/ directory
> * Leave the remaining two BChecks in /other/ as this PR
> 
> This is so we maintain repo hygiene.
> 
> Thank you in advance from all at PortSwigger.

I can accept these changes. output.txt is used to locate the original key corresponding to the encrypted 'rememberMe' value. However, in future updates, I can include them in comments for easier reference. Thank you.

2023-09-14 07:38 UTC, olliewuk approved these changes
thank you for that.

2023-09-14 08:04 UTC, PortSwiggerWiener approved these changes
Looks good. Thanks for the changes and your patience 👍

2023-09-14 08:04 UTC, merged