CVE-2023-39141 Aria2 WebUI - Path Traversal
PortSwigger/BChecks pull request #127
Opened 2023-10-04 03:21 UTC by j0hnZ3RA

2023-10-04 07:01 UTC, PortSwiggerWiener reviewed
Looks good. A potential improvement would be to check that the base response fingerprints Aria2 somehow to differentiate this from generic path traversal.

2023-10-04 20:29 UTC, j0hnZ3RA commented
Thank you for the feedback!

I added a previous step to the base response where it is possible to identify it as Aria2 WebUI. Now we are more certain of the result.

Thank you.

2023-10-05 07:46 UTC, Michelle-PortSwigger requested changes

2023-10-05 07:46 UTC, Michelle-PortSwigger commented on vulnerabilities-CVEd/CVE-2023-39141 Aria2 WebUI - Path Traversal.bcheck
> +    if "Aria2 WebUI" in {check1.response.body} and {check2.response.status_code} is "200" and "root" in {check2.response.body} then
A very small thing, but could you indent this block?

2023-10-05 16:52 UTC, j0hnZ3RA commented on vulnerabilities-CVEd/CVE-2023-39141 Aria2 WebUI - Path Traversal.bcheck
> +    potential_path = "/../../../../etc/passwd"
Done!

2023-10-05 16:52 UTC, j0hnZ3RA commented on vulnerabilities-CVEd/CVE-2023-39141 Aria2 WebUI - Path Traversal.bcheck
> +    if "Aria2 WebUI" in {check1.response.body} and {check2.response.status_code} is "200" and "root" in {check2.response.body} then
Done!

2023-10-05 16:53 UTC, j0hnZ3RA reviewed
Done!

2023-10-06 09:49 UTC, Michelle-PortSwigger approved these changes

2023-10-06 09:50 UTC, Michelle-PortSwigger approved these changes
Thanks for making the revisions. Looks good :)

2023-10-06 09:51 UTC, PortSwiggerWiener approved these changes
Looks good. 👍

2023-10-06 09:51 UTC, merged

2024-02-20 14:17 UTC, michael-eaton-portswigger commented
@j0hnZ3RA As a contributor to our GitHub repository, we would like to invite you to our closed Discord community.

It is a place where passionate Burp users, including people who directly work on building and developing Burp here at PortSwigger, can talk about the tooling and web security in general.

If you would like to join, please email us at support@portswigger.net and we will send over an invite link.

Thank you!