Updated the "Hidden Input Field Detection at Response Level (Passive)" Finding
PortSwigger/BChecks pull request #231
Opened 2024-09-27 20:29 UTC by LabMC

### Overview 
- **CONTEXT**: The purpose of this request is to update the "vulnerability-classes/injection/Detecting hidden input fields for XSS.bcheck" URL.
    - I wanted to create a BCheck which checks for hidden XSS fields based on: https://portswigger.net/research/exploiting-xss-in-hidden-inputs-and-meta-tags
- The current version of this bcheck only checks if ```<input>``` has ```type="hidden"``` as its very first attribute.
- The current version of this bcheck also does not consider hidden fields via ```style="display: none;"```
- I've also provided additions to the detail & remediation text which provides an easy example for how users should test Hidden Input findings for XSS.

**Ask**: As this is a significant update to a pre-existing bcheck file, please let me know what the correct syntax is for multiple authors.

### BCheck Contributions

* [X] BCheck compiles and executes as expected
* [X] BCheck contains appropriate metadata (name, version, author, description and appropriate tags)
* [X] Only .bcheck files have been added or modified
* [X] BCheck is in the appropriate folder
* [X] PR contains single or limited number of BChecks (Multiple PRs are preferred)
* [X] BCheck attempts to minimize false positives

2024-10-03 10:53 UTC, Hannah-PortSwigger requested changes
Thank you for the additional validation that you've added to this BCheck.

We have some feedback around the styling of the issue detail and remediation advice to make this easier to read.

2024-10-03 10:53 UTC, Hannah-PortSwigger commented on vulnerability-classes/injection/Detecting hidden input fields for XSS.bcheck
> +    # Issue Details:
Splitting the issue details and remediation advice into small chunks makes this code difficult to read. Can you please inline these into the `report issue:` block.

2024-10-03 10:53 UTC, Hannah-PortSwigger commented on vulnerability-classes/injection/Detecting hidden input fields for XSS.bcheck
> +    id_01 = `- An '<input>' HTML field with the 'type="hidden"' or 'style="display: none;"' attribute has been detected.\n    - This HTML field may be suseptible to XSS injections.`
Small typo: susceptible

2024-10-03 10:53 UTC, Hannah-PortSwigger commented on vulnerability-classes/injection/Detecting hidden input fields for XSS.bcheck
> +    ir_09 = `\n    > SANITIZE & REEVALUATE: Perform sanatization on non-whitelisted characters once to convert these values into safer alternatives.`
Small typo: sanitization

2024-10-03 10:53 UTC, Hannah-PortSwigger commented on vulnerability-classes/injection/Detecting hidden input fields for XSS.bcheck
> +    ir_12 = `\n    > For example: '<' becomes '&lt;', '>' becomes '&gt;', '&' becomes '&amp', '"' becomes '&quot', & etcetera.`
Small typo: No need for the "& etcetera." - this can just be "etc." or "et cetera."

2024-10-24 13:26 UTC, PortSwiggerWiener approved these changes
Looks good 👍

2024-10-24 13:26 UTC, Hannah-PortSwigger approved these changes

2024-10-24 13:26 UTC, merged