Added "IBM Websphere Source File Publicly Accessible"
PortSwigger/BChecks pull request #25
Opened 2023-07-04 15:50 UTC by Anof-cyber

2023-07-04 17:15 UTC, genuinemoses requested changes
Hi @Anof-cyber, the lines 11,12 do not have proper indentation, and lines 8,14 can be removed to reduce the Lines of Code(LOC,) and add a extra or End of Line(EOL) as the last line.

2023-07-05 10:53 UTC, genuinemoses approved these changes
Reviewed all the commits, the branch is ready for the merge.

2023-07-05 10:58 UTC, genuinemoses approved these changes
@A-J-C, @olliewuk, @AlexPortSwigger, an additional review is required.

2023-07-05 12:20 UTC, A-J-C approved these changes

2023-07-05 12:31 UTC, merged