Added Spring4Shell.bcheck rule
PortSwigger/BChecks pull request #84
Opened 2023-08-17 17:57 UTC by GiriRaj249

## About

Added a rule to check for Spring4Shell vulnerability by targeting GET requests. Following are the conditions that I have used to validate the existence of the bug :

- status code is "400"
- response body should contain `java.lang.IllegalArgumentException` error

2023-08-18 09:30 UTC, olliewuk requested changes

2023-08-18 09:30 UTC, olliewuk commented on vulnerability-classes/injection/Spring4Shell.bcheck
> +		if {check.response.status_code} is "400" and "java.lang.IllegalArgumentException" in {check.response.body} then
can you fix in identing please?

2023-08-18 11:27 UTC, GiriRaj249 commented on vulnerability-classes/injection/Spring4Shell.bcheck
> +		if {check.response.status_code} is "400" and "java.lang.IllegalArgumentException" in {check.response.body} then
Yes, I have fixed the indentation on the latest commit.

2023-08-21 08:17 UTC, GiriRaj249 commented on vulnerability-classes/injection/Spring4Shell.bcheck
> +		if {check.response.status_code} is "400" and "java.lang.IllegalArgumentException" in {check.response.body} then
Hey, olliewuk!! good day. Any update on the commit? I have requested a review

2023-08-21 08:18 UTC, olliewuk approved these changes

2023-08-21 08:49 UTC, GiriRaj249 commented
Hey Team,

I got 1 approval from Olliewuk, but this merge required at least 2 approvals. When can I expect my commit to be pushed on the BCheck repo ?

Awaiting your approval/response. Thanks in advance

2023-08-23 08:57 UTC, GiriRaj249 commented
Hey Team Portswigger,

Any update that i need to be aware off?

2023-08-23 09:57 UTC, Hannah-PortSwigger approved these changes

2023-08-23 09:57 UTC, merged