CVE-2023-38035
PortSwigger/BChecks pull request #93
Opened 2023-08-27 17:59 UTC by DolphFlynn

2023-08-28 07:35 UTC, olliewuk requested changes

2023-08-28 07:35 UTC, olliewuk commented on vulnerabilities-CVEd/CVE-2023-38035 - Ivanti Sentry - Auth Bypass.bcheck
> +Host: {base.request.url.host}
Can you fix this indenting please?

2023-08-28 07:37 UTC, olliewuk commented on vulnerabilities-CVEd/CVE-2023-38035 - Ivanti Sentry - Auth Bypass.bcheck
> +Host: {base.request.url.host}
ignore me, I suspect it can't be resolved as we need the raw request.

2023-08-28 07:37 UTC, olliewuk approved these changes

2023-08-28 09:41 UTC, DolphFlynn commented on vulnerabilities-CVEd/CVE-2023-38035 - Ivanti Sentry - Auth Bypass.bcheck
> +Host: {base.request.url.host}
I had assumed this was the case and formatted accordingly, but from a brief test the logic seems to be that any newline is normalised to 0xd0xa (even within the HTTP body) and any leading space after a newline is stripped (even within the HTTP body). The latter seems somewhat overzealous to me.

With respect to this PR, I'm happy to update the formatting if required.

2023-08-29 08:36 UTC, Hannah-PortSwigger approved these changes

2023-08-29 08:36 UTC, merged